spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatadb
    username: admin
    password: 2001
  jpa:
    hibernate:
      ddl-auto: validate
#  security:
#    user:
#      name: orxan
#      password: 12345
server:
  port: 8088
#  servlet:
#    context-path: /api

