spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatadb
    username: admin
    password: 2001
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8088
  servlet:
    context-path: /api

