spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatadb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
#  security:
#    user:
#      name: orxan
#      password: 12345
server:
  port: 8088
#  servlet:
#    context-path: /api

